spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_ms
    username: root
    password: 111111
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2952234243@qq.com
    #授权码
    password: kxfzzggepmzjdggg
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tGw2F7Vnxra5EmbB7Yn
    accessKeySecret: 0RUh7rw6Vec3Ufe9oWHLOTFnDB4grk
    bucketName: web-xugq
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#spring邮箱发送服务


