spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_ms
    username: root
    password: 111111
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2952234243@qq.com
    #授权码
    password: kxfzzggepmzjdggg
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


alipay:
  appId: 9021000142667188
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBVtullSwksqQ0Yw8NE/hnaMCj8EGV7EpeIl2QIBXrmvmVW+2BeryQk8lZN97l3zx5xLLr+TaLCvWVGVLfA6J97lu0ydSewxQ+Dl+uglj/pLHGSoVEUzz4AA9dZ4OXFW2mO1bLSPmqPY2sz699Zf1DKbgS3x2DYl4zL7J0Rv2ZJSJr9MBrNa3hqTgyaiK3giTuSe7UyoJs2fyMGGoWL8uoZW1uZkKe3LZhtTDbHd992JElonB9t8/nLVpa1+hVb5OUn1HUbIqfdmLguxmyd/B5oXUz3jEItLIDVIVwI43t9r5WGoK9u6n2qD82jVe/RPhNjJqw6kOYBQcnWQMS9jBvAgMBAAECggEAAaPXTycwExsMx/lFlJXfPXhvkOSYAE2pt73Zz90ISh+B8KnkvhKPV4n4MKBrvCBzhNvApQtY7LRr3sMecON76PrfwNAaWRUCKbNG9VCDzmIJOwlw3SftCvv9NeL9ISpNZKE1/YfkWotDQ6CyifWEG5jo05xupF7X8PA25BCOYKW6Q8kE+v/W69lCjB3vmVB1I6XrElHbj7ZTu/773yI+AnYk0KTpL0+WwEqDf3hTdeTUYDvBvJuUlrqS9oz7VMBqbAp7bs9ryuXuLfb0x6RgHdQMtdEa0l1Nxyt7b8yjsht+0Aik/8Ohgebc0OoN8/43ejNJBZuROXalYV/ShQjiGQKBgQDFUg1/I+t0kgNDlMMZg0dspiZBCou95+rJ4WLh1HkuQOiYEdHexw14m+e6CJ57NSNH6y6d0x7zWJo85iQ0yZP7FG28fwnf8Vmlkx+WRKYCnCvzKmcfiS771EYhNj2XJvRZuJVDa0hTv0scTJ0gdsykGmssSLeQq/NAvbtVC2fL8wKBgQCnzWqP1CFGp2PofDucEqIW0w7RJNZe/bqwkJxP2FIkbUsmcolaOYj74l7vR52ab29F0fp0mFLe7RmGd33Tqr333Aad3oStC9k/9Do+i/Za20Ba9EQKk4H4lFQihaiByqWw2hFn3ES8VDUs1y+3uwRaO4V7r8uMtoGmXie5eMyUlQKBgHPtyVAxYlySjKhf9mA+6O/EjiUYdRGV+DOz38yecLPkHsN5dLxWZmu97V83QSVSCvBuFG1VZJHENJoi/JKm+/JABlkAqmSQAANvdNdsbbyK1KeA+iVlC92Y0bshiv4LPPSZpdh+Z3gMo6x0trwkEAc6Hk1eS7sLy1b2IeHNWaZRAoGAYVZG+ieTJejzi2iFK4OjgpnrfmZf87o7ETDRe3+AJqE/do36HtxBGdu2NhbU1UDOyzGClx/E8ouWwumNk7r3d0+qhukNDVRSMUb6gk2uGgYUzq3iyj/GpOtl4qClnqRueKgGcLjVJmmybtBkXa+eVrkwNQ9Eg9taWadEY9Iu2gECgYEAnbq52WKogI2Dszmgl284zTLlSMTAhHUiDmiApyb0kcKB85iLCA73SviAY4f2aFqM/ifOxtiIFwNUf6VQSYG5w43hHAs4m3U28fUo72e1YFpX7X42XIZgdND+aIPFLB1rhdyJjJX5y/SBFFM1ujRVzS/0kR5KY5/qLm4EEEzGtHk=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlCIy8oo/v11wNZaZcr9ZL2ZFx2H6IQd41DfyfNKtf3tgmK+BTeVGMwjmVtnNNtTfySe4hbpvN2GZpGMSC1/qEJD3ed9CVyFkmfj/TveLZwWbAjKe3rEIoDJdrwpEp7tMiPiydybEO2x4UwR0UN00vk9yub4XlriRIrC9GGFE1l3rquVfufaYYSz8MrSd1BKLqSB89pSRWOjkXikXjHCXnzp4/bpH9X5FwF0mCMYpBe0dP0DWrLH+yGEETmpCUWZSPLYokBQhwZ5DykxiL2yX9StEWvNHis/NBFOqc8Ibr9UZfpUbKXd6EWqtxVFjv+gLxyPlCa55xytjUwvq3SsJkQIDAQAB
  notifyUrl: http://xgq.free.idcfengye.com/alipay/notify


aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tGw2F7Vnxra5EmbB7Yn
    accessKeySecret: 0RUh7rw6Vec3Ufe9oWHLOTFnDB4grk
    bucketName: web-xugq
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#spring邮箱发送服务


